# Enable bstats
bstats: true
# Hook options
hook:
  bukkit:
    # Should we hook the Bukkit event?
    enabled: true
    # Should we call the BukkitListenerEvent?
    call-event: false
    # Should we use reflection to get player in unknown events?
    use-reflection-to-get-event-player: true

  protocollib:
    # Should we hook the ProtocolLib packet listener?
    enabled: true
    # Should we call the ProtocolLibPacketEvent?
    call-event: false

  netty:
    # Should we hook the netty pipeline?
    enabled: true
    # Should we call the NettyCodecEvent?
    call-event: false

  packetevents:
    # Should we hook the PacketEvents packet listener?
    enabled: true
    # Should we call the PacketEventsPacketEvent?
    call-event: false